Name=input("Enter your name:")
Branch=input("Enter your branch:")
Gender=input("Enter gender:")
College=input("Enter your college name:")
Age=input("Enter your Age:")
print("Name is :", Name)
print("Branch is :", Branch)
print("Gender is :", Gender)
print("College is :" ,College)
print("Age is :", Age)
